# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'desktop_viewfctpOP.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTextEdit, QWidget)

class Ui_DesktopView(object):
    def setupUi(self, DesktopView):
        if not DesktopView.objectName():
            DesktopView.setObjectName(u"DesktopView")
        DesktopView.resize(1038, 755)
        font = QFont()
        font.setFamilies([u"Tahoma"])
        font.setPointSize(8)
        DesktopView.setFont(font)
        DesktopView.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.centralwidget = QWidget(DesktopView)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(8, 309, 921, 393))
        self.tabProgram = QWidget()
        self.tabProgram.setObjectName(u"tabProgram")
        self.new_program = QPushButton(self.tabProgram)
        self.new_program.setObjectName(u"new_program")
        self.new_program.setGeometry(QRect(16, 41, 120, 24))
        self.ProgramLoadButton = QPushButton(self.tabProgram)
        self.ProgramLoadButton.setObjectName(u"ProgramLoadButton")
        self.ProgramLoadButton.setGeometry(QRect(16, 90, 120, 24))
        self.ProgramSaveButton = QPushButton(self.tabProgram)
        self.ProgramSaveButton.setObjectName(u"ProgramSaveButton")
        self.ProgramSaveButton.setGeometry(QRect(16, 130, 120, 24))
        self.ProgramSaveAsButton = QPushButton(self.tabProgram)
        self.ProgramSaveAsButton.setObjectName(u"ProgramSaveAsButton")
        self.ProgramSaveAsButton.setGeometry(QRect(16, 170, 120, 24))
        self.lineEdit = QLineEdit(self.tabProgram)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(190, 130, 113, 22))
        self.lineEdit_2 = QLineEdit(self.tabProgram)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(190, 160, 113, 22))
        self.label = QLabel(self.tabProgram)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(16, 16, 137, 16))
        self.line = QFrame(self.tabProgram)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(16, 33, 806, 2))
        self.line.setFrameShadow(QFrame.Shadow.Plain)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.tabWidget.addTab(self.tabProgram, "")
        self.tabGCode = QWidget()
        self.tabGCode.setObjectName(u"tabGCode")
        self.tabWidget.addTab(self.tabGCode, "")
        self.tabCNC = QWidget()
        self.tabCNC.setObjectName(u"tabCNC")
        self.tabWidget.addTab(self.tabCNC, "")
        self.tabJOG = QWidget()
        self.tabJOG.setObjectName(u"tabJOG")
        self.cncJogCommandXMButton = QPushButton(self.tabJOG)
        self.cncJogCommandXMButton.setObjectName(u"cncJogCommandXMButton")
        self.cncJogCommandXMButton.setGeometry(QRect(16, 14, 80, 24))
        self.cncJogCommandYMButton = QPushButton(self.tabJOG)
        self.cncJogCommandYMButton.setObjectName(u"cncJogCommandYMButton")
        self.cncJogCommandYMButton.setGeometry(QRect(16, 46, 80, 24))
        self.cncJogCommandZMButton = QPushButton(self.tabJOG)
        self.cncJogCommandZMButton.setObjectName(u"cncJogCommandZMButton")
        self.cncJogCommandZMButton.setGeometry(QRect(16, 78, 80, 24))
        self.cncJogCommandAMButton = QPushButton(self.tabJOG)
        self.cncJogCommandAMButton.setObjectName(u"cncJogCommandAMButton")
        self.cncJogCommandAMButton.setGeometry(QRect(16, 110, 80, 24))
        self.cncJogCommandBMButton = QPushButton(self.tabJOG)
        self.cncJogCommandBMButton.setObjectName(u"cncJogCommandBMButton")
        self.cncJogCommandBMButton.setGeometry(QRect(16, 142, 80, 24))
        self.cncJogCommandCMButton = QPushButton(self.tabJOG)
        self.cncJogCommandCMButton.setObjectName(u"cncJogCommandCMButton")
        self.cncJogCommandCMButton.setGeometry(QRect(16, 174, 80, 24))
        self.cncJogCommandYPButton = QPushButton(self.tabJOG)
        self.cncJogCommandYPButton.setObjectName(u"cncJogCommandYPButton")
        self.cncJogCommandYPButton.setGeometry(QRect(104, 46, 80, 24))
        self.cncJogCommandAPButton = QPushButton(self.tabJOG)
        self.cncJogCommandAPButton.setObjectName(u"cncJogCommandAPButton")
        self.cncJogCommandAPButton.setGeometry(QRect(104, 110, 80, 24))
        self.cncJogCommandBPButton = QPushButton(self.tabJOG)
        self.cncJogCommandBPButton.setObjectName(u"cncJogCommandBPButton")
        self.cncJogCommandBPButton.setGeometry(QRect(104, 142, 80, 24))
        self.cncJogCommandXPButton = QPushButton(self.tabJOG)
        self.cncJogCommandXPButton.setObjectName(u"cncJogCommandXPButton")
        self.cncJogCommandXPButton.setGeometry(QRect(104, 14, 80, 24))
        self.cncJogCommandCPButton = QPushButton(self.tabJOG)
        self.cncJogCommandCPButton.setObjectName(u"cncJogCommandCPButton")
        self.cncJogCommandCPButton.setGeometry(QRect(104, 174, 80, 24))
        self.cncJogCommandZPButton = QPushButton(self.tabJOG)
        self.cncJogCommandZPButton.setObjectName(u"cncJogCommandZPButton")
        self.cncJogCommandZPButton.setGeometry(QRect(104, 78, 80, 24))
        self.pushButton_13 = QPushButton(self.tabJOG)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(825, 46, 80, 24))
        self.pushButton_14 = QPushButton(self.tabJOG)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(825, 174, 80, 24))
        self.pushButton_15 = QPushButton(self.tabJOG)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(825, 14, 80, 24))
        self.pushButton_16 = QPushButton(self.tabJOG)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(825, 142, 80, 24))
        self.pushButton_17 = QPushButton(self.tabJOG)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(825, 110, 80, 24))
        self.pushButton_18 = QPushButton(self.tabJOG)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(825, 78, 80, 24))
        self.lineEdit_3 = QLineEdit(self.tabJOG)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(714, 14, 100, 22))
        self.tabWidget.addTab(self.tabJOG, "")
        self.tabOverrides = QWidget()
        self.tabOverrides.setObjectName(u"tabOverrides")
        self.tabWidget.addTab(self.tabOverrides, "")
        self.tabHoming = QWidget()
        self.tabHoming.setObjectName(u"tabHoming")
        self.tabWidget.addTab(self.tabHoming, "")
        self.tabMDI = QWidget()
        self.tabMDI.setObjectName(u"tabMDI")
        self.tabWidget.addTab(self.tabMDI, "")
        self.tabDIO = QWidget()
        self.tabDIO.setObjectName(u"tabDIO")
        self.tabWidget.addTab(self.tabDIO, "")
        self.tabAIO = QWidget()
        self.tabAIO.setObjectName(u"tabAIO")
        self.tabWidget.addTab(self.tabAIO, "")
        self.tabScanningLaser = QWidget()
        self.tabScanningLaser.setObjectName(u"tabScanningLaser")
        self.tabWidget.addTab(self.tabScanningLaser, "")
        self.tabMachiningInfo = QWidget()
        self.tabMachiningInfo.setObjectName(u"tabMachiningInfo")
        self.tabWidget.addTab(self.tabMachiningInfo, "")
        self.tabUIDialogs = QWidget()
        self.tabUIDialogs.setObjectName(u"tabUIDialogs")
        self.uidAboutButton = QPushButton(self.tabUIDialogs)
        self.uidAboutButton.setObjectName(u"uidAboutButton")
        self.uidAboutButton.setGeometry(QRect(690, 280, 161, 41))
        self.uidATCManagementButton = QPushButton(self.tabUIDialogs)
        self.uidATCManagementButton.setObjectName(u"uidATCManagementButton")
        self.uidATCManagementButton.setGeometry(QRect(690, 60, 161, 41))
        self.uidBoardEtherCATMonitorButton = QPushButton(self.tabUIDialogs)
        self.uidBoardEtherCATMonitorButton.setObjectName(u"uidBoardEtherCATMonitorButton")
        self.uidBoardEtherCATMonitorButton.setGeometry(QRect(350, 110, 161, 41))
        self.uidBoardFirmwareManagerButton = QPushButton(self.tabUIDialogs)
        self.uidBoardFirmwareManagerButton.setObjectName(u"uidBoardFirmwareManagerButton")
        self.uidBoardFirmwareManagerButton.setGeometry(QRect(520, 60, 161, 41))
        self.uidBoardMonitorButton = QPushButton(self.tabUIDialogs)
        self.uidBoardMonitorButton.setObjectName(u"uidBoardMonitorButton")
        self.uidBoardMonitorButton.setGeometry(QRect(350, 10, 161, 41))
        self.uidBoardSettingsButton = QPushButton(self.tabUIDialogs)
        self.uidBoardSettingsButton.setObjectName(u"uidBoardSettingsButton")
        self.uidBoardSettingsButton.setGeometry(QRect(350, 60, 161, 41))
        self.uidToolsLibraryButton = QPushButton(self.tabUIDialogs)
        self.uidToolsLibraryButton.setObjectName(u"uidToolsLibraryButton")
        self.uidToolsLibraryButton.setGeometry(QRect(180, 110, 161, 41))
        self.uidChangeBoardIPButton = QPushButton(self.tabUIDialogs)
        self.uidChangeBoardIPButton.setObjectName(u"uidChangeBoardIPButton")
        self.uidChangeBoardIPButton.setGeometry(QRect(520, 10, 161, 41))
        self.uidWorkCoordinatesButton = QPushButton(self.tabUIDialogs)
        self.uidWorkCoordinatesButton.setObjectName(u"uidWorkCoordinatesButton")
        self.uidWorkCoordinatesButton.setGeometry(QRect(180, 10, 161, 41))
        self.uidProgramSettingsButton = QPushButton(self.tabUIDialogs)
        self.uidProgramSettingsButton.setObjectName(u"uidProgramSettingsButton")
        self.uidProgramSettingsButton.setGeometry(QRect(10, 10, 161, 41))
        self.uidParametersLibraryButton = QPushButton(self.tabUIDialogs)
        self.uidParametersLibraryButton.setObjectName(u"uidParametersLibraryButton")
        self.uidParametersLibraryButton.setGeometry(QRect(180, 60, 161, 41))
        self.uidMacrosManagementButton = QPushButton(self.tabUIDialogs)
        self.uidMacrosManagementButton.setObjectName(u"uidMacrosManagementButton")
        self.uidMacrosManagementButton.setGeometry(QRect(690, 10, 161, 41))
        self.tabWidget.addTab(self.tabUIDialogs, "")
        self.tabSystemInfo = QWidget()
        self.tabSystemInfo.setObjectName(u"tabSystemInfo")
        self.systemInfoEdit = QTextEdit(self.tabSystemInfo)
        self.systemInfoEdit.setObjectName(u"systemInfoEdit")
        self.systemInfoEdit.setGeometry(QRect(0, 0, 921, 393))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.systemInfoEdit.sizePolicy().hasHeightForWidth())
        self.systemInfoEdit.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamilies([u"DejaVu Sans Mono"])
        font1.setPointSize(8)
        self.systemInfoEdit.setFont(font1)
        self.systemInfoEdit.setFrameShape(QFrame.Shape.NoFrame)
        self.systemInfoEdit.setReadOnly(True)
        self.tabWidget.addTab(self.tabSystemInfo, "")
        self.mcsTitleLabel = QLabel(self.centralwidget)
        self.mcsTitleLabel.setObjectName(u"mcsTitleLabel")
        self.mcsTitleLabel.setGeometry(QRect(16, 13, 145, 17))
        sizePolicy.setHeightForWidth(self.mcsTitleLabel.sizePolicy().hasHeightForWidth())
        self.mcsTitleLabel.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setFamilies([u"Roboto"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.mcsTitleLabel.setFont(font2)
        self.mcsTitleLabel.setFrameShape(QFrame.Shape.NoFrame)
        self.mcsTitleLabel.setFrameShadow(QFrame.Shadow.Plain)
        self.mcsTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.prpTitleLabel = QLabel(self.centralwidget)
        self.prpTitleLabel.setObjectName(u"prpTitleLabel")
        self.prpTitleLabel.setGeometry(QRect(184, 13, 145, 17))
        sizePolicy.setHeightForWidth(self.prpTitleLabel.sizePolicy().hasHeightForWidth())
        self.prpTitleLabel.setSizePolicy(sizePolicy)
        self.prpTitleLabel.setFont(font2)
        self.prpTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.avlTitleLabel = QLabel(self.centralwidget)
        self.avlTitleLabel.setObjectName(u"avlTitleLabel")
        self.avlTitleLabel.setGeometry(QRect(352, 13, 145, 17))
        sizePolicy.setHeightForWidth(self.avlTitleLabel.sizePolicy().hasHeightForWidth())
        self.avlTitleLabel.setSizePolicy(sizePolicy)
        self.avlTitleLabel.setFont(font2)
        self.avlTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.wofTitleLabel = QLabel(self.centralwidget)
        self.wofTitleLabel.setObjectName(u"wofTitleLabel")
        self.wofTitleLabel.setGeometry(QRect(517, 13, 145, 17))
        sizePolicy.setHeightForWidth(self.wofTitleLabel.sizePolicy().hasHeightForWidth())
        self.wofTitleLabel.setSizePolicy(sizePolicy)
        self.wofTitleLabel.setFont(font2)
        self.wofTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mtpTitleLabel = QLabel(self.centralwidget)
        self.mtpTitleLabel.setObjectName(u"mtpTitleLabel")
        self.mtpTitleLabel.setGeometry(QRect(16, 149, 145, 17))
        sizePolicy.setHeightForWidth(self.mtpTitleLabel.sizePolicy().hasHeightForWidth())
        self.mtpTitleLabel.setSizePolicy(sizePolicy)
        self.mtpTitleLabel.setFont(font2)
        self.mtpTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ptpTitleLabel = QLabel(self.centralwidget)
        self.ptpTitleLabel.setObjectName(u"ptpTitleLabel")
        self.ptpTitleLabel.setGeometry(QRect(184, 149, 145, 17))
        sizePolicy.setHeightForWidth(self.ptpTitleLabel.sizePolicy().hasHeightForWidth())
        self.ptpTitleLabel.setSizePolicy(sizePolicy)
        self.ptpTitleLabel.setFont(font2)
        self.ptpTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.jopTitleLabel = QLabel(self.centralwidget)
        self.jopTitleLabel.setObjectName(u"jopTitleLabel")
        self.jopTitleLabel.setGeometry(QRect(352, 149, 145, 17))
        sizePolicy.setHeightForWidth(self.jopTitleLabel.sizePolicy().hasHeightForWidth())
        self.jopTitleLabel.setSizePolicy(sizePolicy)
        self.jopTitleLabel.setFont(font2)
        self.jopTitleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.machineInfoLabel = QLabel(self.centralwidget)
        self.machineInfoLabel.setObjectName(u"machineInfoLabel")
        self.machineInfoLabel.setGeometry(QRect(520, 149, 145, 17))
        sizePolicy.setHeightForWidth(self.machineInfoLabel.sizePolicy().hasHeightForWidth())
        self.machineInfoLabel.setSizePolicy(sizePolicy)
        self.machineInfoLabel.setFont(font2)
        self.machineInfoLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolInfoPanel = QFrame(self.centralwidget)
        self.toolInfoPanel.setObjectName(u"toolInfoPanel")
        self.toolInfoPanel.setGeometry(QRect(8, 275, 921, 25))
        self.toolInfoPanel.setFrameShape(QFrame.Shape.StyledPanel)
        self.toolInfoPanel.setFrameShadow(QFrame.Shadow.Plain)
        self.toolInfoLabel = QLabel(self.toolInfoPanel)
        self.toolInfoLabel.setObjectName(u"toolInfoLabel")
        self.toolInfoLabel.setGeometry(QRect(11, 0, 901, 25))
        sizePolicy.setHeightForWidth(self.toolInfoLabel.sizePolicy().hasHeightForWidth())
        self.toolInfoLabel.setSizePolicy(sizePolicy)
        self.toolInfoLabel.setTextFormat(Qt.TextFormat.PlainText)
        self.CommandsFrame = QFrame(self.centralwidget)
        self.CommandsFrame.setObjectName(u"CommandsFrame")
        self.CommandsFrame.setGeometry(QRect(936, 8, 96, 723))
        self.CommandsFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.CommandsFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.CommandsLabel = QLabel(self.CommandsFrame)
        self.CommandsLabel.setObjectName(u"CommandsLabel")
        self.CommandsLabel.setGeometry(QRect(8, 2, 80, 17))
        sizePolicy.setHeightForWidth(self.CommandsLabel.sizePolicy().hasHeightForWidth())
        self.CommandsLabel.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setFamilies([u"Tahoma"])
        font3.setPointSize(8)
        font3.setBold(True)
        self.CommandsLabel.setFont(font3)
        self.CommandsLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.CNCConnectionOpenButton = QPushButton(self.CommandsFrame)
        self.CNCConnectionOpenButton.setObjectName(u"CNCConnectionOpenButton")
        self.CNCConnectionOpenButton.setGeometry(QRect(8, 22, 80, 54))
        self.CNCConnectionCloseButton = QPushButton(self.CommandsFrame)
        self.CNCConnectionCloseButton.setObjectName(u"CNCConnectionCloseButton")
        self.CNCConnectionCloseButton.setGeometry(QRect(8, 78, 80, 54))
        self.ServerConnectDisconnectButton = QPushButton(self.centralwidget)
        self.ServerConnectDisconnectButton.setObjectName(u"ServerConnectDisconnectButton")
        self.ServerConnectDisconnectButton.setGeometry(QRect(767, 709, 161, 22))
        self.mcsXLabel = QLabel(self.centralwidget)
        self.mcsXLabel.setObjectName(u"mcsXLabel")
        self.mcsXLabel.setGeometry(QRect(16, 38, 10, 16))
        font4 = QFont()
        font4.setFamilies([u"Roboto"])
        font4.setPointSize(9)
        self.mcsXLabel.setFont(font4)
        self.mcsYLabel = QLabel(self.centralwidget)
        self.mcsYLabel.setObjectName(u"mcsYLabel")
        self.mcsYLabel.setGeometry(QRect(16, 54, 10, 16))
        self.mcsYLabel.setFont(font4)
        self.mcsZLabel = QLabel(self.centralwidget)
        self.mcsZLabel.setObjectName(u"mcsZLabel")
        self.mcsZLabel.setGeometry(QRect(16, 70, 10, 16))
        self.mcsZLabel.setFont(font4)
        self.mcsALabel = QLabel(self.centralwidget)
        self.mcsALabel.setObjectName(u"mcsALabel")
        self.mcsALabel.setGeometry(QRect(16, 86, 10, 16))
        self.mcsALabel.setFont(font4)
        self.mcsBLabel = QLabel(self.centralwidget)
        self.mcsBLabel.setObjectName(u"mcsBLabel")
        self.mcsBLabel.setGeometry(QRect(16, 102, 10, 16))
        self.mcsBLabel.setFont(font4)
        self.mcsXValue = QLabel(self.centralwidget)
        self.mcsXValue.setObjectName(u"mcsXValue")
        self.mcsXValue.setGeometry(QRect(40, 38, 120, 16))
        font5 = QFont()
        font5.setFamilies([u"DejaVu Sans Mono"])
        font5.setPointSize(9)
        self.mcsXValue.setFont(font5)
        self.mcsXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mcsYValue = QLabel(self.centralwidget)
        self.mcsYValue.setObjectName(u"mcsYValue")
        self.mcsYValue.setGeometry(QRect(40, 54, 120, 16))
        self.mcsYValue.setFont(font5)
        self.mcsYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mcsZValue = QLabel(self.centralwidget)
        self.mcsZValue.setObjectName(u"mcsZValue")
        self.mcsZValue.setGeometry(QRect(40, 70, 120, 16))
        self.mcsZValue.setFont(font5)
        self.mcsZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mcsAValue = QLabel(self.centralwidget)
        self.mcsAValue.setObjectName(u"mcsAValue")
        self.mcsAValue.setGeometry(QRect(40, 86, 120, 16))
        self.mcsAValue.setFont(font5)
        self.mcsAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mcsBValue = QLabel(self.centralwidget)
        self.mcsBValue.setObjectName(u"mcsBValue")
        self.mcsBValue.setGeometry(QRect(40, 102, 120, 16))
        self.mcsBValue.setFont(font5)
        self.mcsBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mcsCLabel = QLabel(self.centralwidget)
        self.mcsCLabel.setObjectName(u"mcsCLabel")
        self.mcsCLabel.setGeometry(QRect(16, 118, 10, 16))
        self.mcsCLabel.setFont(font4)
        self.mcsCValue = QLabel(self.centralwidget)
        self.mcsCValue.setObjectName(u"mcsCValue")
        self.mcsCValue.setGeometry(QRect(40, 118, 120, 16))
        self.mcsCValue.setFont(font5)
        self.mcsCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsCLabel = QLabel(self.centralwidget)
        self.wcsCLabel.setObjectName(u"wcsCLabel")
        self.wcsCLabel.setGeometry(QRect(187, 118, 10, 16))
        self.wcsCLabel.setFont(font4)
        self.wcsBLabel = QLabel(self.centralwidget)
        self.wcsBLabel.setObjectName(u"wcsBLabel")
        self.wcsBLabel.setGeometry(QRect(187, 102, 10, 16))
        self.wcsBLabel.setFont(font4)
        self.wcsXLabel = QLabel(self.centralwidget)
        self.wcsXLabel.setObjectName(u"wcsXLabel")
        self.wcsXLabel.setGeometry(QRect(187, 38, 10, 16))
        self.wcsXLabel.setFont(font4)
        self.wcsBValue = QLabel(self.centralwidget)
        self.wcsBValue.setObjectName(u"wcsBValue")
        self.wcsBValue.setGeometry(QRect(211, 102, 120, 16))
        self.wcsBValue.setFont(font5)
        self.wcsBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsYLabel = QLabel(self.centralwidget)
        self.wcsYLabel.setObjectName(u"wcsYLabel")
        self.wcsYLabel.setGeometry(QRect(187, 54, 10, 16))
        self.wcsYLabel.setFont(font4)
        self.wcsALabel = QLabel(self.centralwidget)
        self.wcsALabel.setObjectName(u"wcsALabel")
        self.wcsALabel.setGeometry(QRect(187, 86, 10, 16))
        self.wcsALabel.setFont(font4)
        self.wcsXValue = QLabel(self.centralwidget)
        self.wcsXValue.setObjectName(u"wcsXValue")
        self.wcsXValue.setGeometry(QRect(211, 38, 120, 16))
        self.wcsXValue.setFont(font5)
        self.wcsXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsYValue = QLabel(self.centralwidget)
        self.wcsYValue.setObjectName(u"wcsYValue")
        self.wcsYValue.setGeometry(QRect(211, 54, 120, 16))
        self.wcsYValue.setFont(font5)
        self.wcsYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsZValue = QLabel(self.centralwidget)
        self.wcsZValue.setObjectName(u"wcsZValue")
        self.wcsZValue.setGeometry(QRect(211, 70, 120, 16))
        self.wcsZValue.setFont(font5)
        self.wcsZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsCValue = QLabel(self.centralwidget)
        self.wcsCValue.setObjectName(u"wcsCValue")
        self.wcsCValue.setGeometry(QRect(211, 118, 120, 16))
        self.wcsCValue.setFont(font5)
        self.wcsCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsAValue = QLabel(self.centralwidget)
        self.wcsAValue.setObjectName(u"wcsAValue")
        self.wcsAValue.setGeometry(QRect(211, 86, 120, 16))
        self.wcsAValue.setFont(font5)
        self.wcsAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wcsZLabel = QLabel(self.centralwidget)
        self.wcsZLabel.setObjectName(u"wcsZLabel")
        self.wcsZLabel.setGeometry(QRect(187, 70, 10, 16))
        self.wcsZLabel.setFont(font4)
        self.avlYValue = QLabel(self.centralwidget)
        self.avlYValue.setObjectName(u"avlYValue")
        self.avlYValue.setGeometry(QRect(379, 54, 120, 16))
        self.avlYValue.setFont(font5)
        self.avlYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.avlZValue = QLabel(self.centralwidget)
        self.avlZValue.setObjectName(u"avlZValue")
        self.avlZValue.setGeometry(QRect(379, 70, 120, 16))
        self.avlZValue.setFont(font5)
        self.avlZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.avlZLabel = QLabel(self.centralwidget)
        self.avlZLabel.setObjectName(u"avlZLabel")
        self.avlZLabel.setGeometry(QRect(355, 70, 10, 16))
        self.avlZLabel.setFont(font4)
        self.avlXLabel = QLabel(self.centralwidget)
        self.avlXLabel.setObjectName(u"avlXLabel")
        self.avlXLabel.setGeometry(QRect(355, 38, 10, 16))
        self.avlXLabel.setFont(font4)
        self.avlALabel = QLabel(self.centralwidget)
        self.avlALabel.setObjectName(u"avlALabel")
        self.avlALabel.setGeometry(QRect(355, 86, 10, 16))
        self.avlALabel.setFont(font4)
        self.avlBLabel = QLabel(self.centralwidget)
        self.avlBLabel.setObjectName(u"avlBLabel")
        self.avlBLabel.setGeometry(QRect(355, 102, 10, 16))
        self.avlBLabel.setFont(font4)
        self.avlCLabel = QLabel(self.centralwidget)
        self.avlCLabel.setObjectName(u"avlCLabel")
        self.avlCLabel.setGeometry(QRect(355, 118, 10, 16))
        self.avlCLabel.setFont(font4)
        self.avlCValue = QLabel(self.centralwidget)
        self.avlCValue.setObjectName(u"avlCValue")
        self.avlCValue.setGeometry(QRect(379, 118, 120, 16))
        self.avlCValue.setFont(font5)
        self.avlCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.avlYLabel = QLabel(self.centralwidget)
        self.avlYLabel.setObjectName(u"avlYLabel")
        self.avlYLabel.setGeometry(QRect(355, 54, 10, 16))
        self.avlYLabel.setFont(font4)
        self.avlBValue = QLabel(self.centralwidget)
        self.avlBValue.setObjectName(u"avlBValue")
        self.avlBValue.setGeometry(QRect(379, 102, 120, 16))
        self.avlBValue.setFont(font5)
        self.avlBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.avlXValue = QLabel(self.centralwidget)
        self.avlXValue.setObjectName(u"avlXValue")
        self.avlXValue.setGeometry(QRect(379, 38, 120, 16))
        self.avlXValue.setFont(font5)
        self.avlXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.avlAValue = QLabel(self.centralwidget)
        self.avlAValue.setObjectName(u"avlAValue")
        self.avlAValue.setGeometry(QRect(379, 86, 120, 16))
        self.avlAValue.setFont(font5)
        self.avlAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wofYValue = QLabel(self.centralwidget)
        self.wofYValue.setObjectName(u"wofYValue")
        self.wofYValue.setGeometry(QRect(544, 54, 120, 16))
        self.wofYValue.setFont(font5)
        self.wofYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wofZValue = QLabel(self.centralwidget)
        self.wofZValue.setObjectName(u"wofZValue")
        self.wofZValue.setGeometry(QRect(544, 70, 120, 16))
        self.wofZValue.setFont(font5)
        self.wofZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wofZLabel = QLabel(self.centralwidget)
        self.wofZLabel.setObjectName(u"wofZLabel")
        self.wofZLabel.setGeometry(QRect(520, 70, 10, 16))
        self.wofZLabel.setFont(font4)
        self.wofXLabel = QLabel(self.centralwidget)
        self.wofXLabel.setObjectName(u"wofXLabel")
        self.wofXLabel.setGeometry(QRect(520, 38, 10, 16))
        self.wofXLabel.setFont(font4)
        self.wofALabel = QLabel(self.centralwidget)
        self.wofALabel.setObjectName(u"wofALabel")
        self.wofALabel.setGeometry(QRect(520, 86, 10, 16))
        self.wofALabel.setFont(font4)
        self.wofBLabel = QLabel(self.centralwidget)
        self.wofBLabel.setObjectName(u"wofBLabel")
        self.wofBLabel.setGeometry(QRect(520, 102, 10, 16))
        self.wofBLabel.setFont(font4)
        self.wofCLabel = QLabel(self.centralwidget)
        self.wofCLabel.setObjectName(u"wofCLabel")
        self.wofCLabel.setGeometry(QRect(520, 118, 10, 16))
        self.wofCLabel.setFont(font4)
        self.wofCValue = QLabel(self.centralwidget)
        self.wofCValue.setObjectName(u"wofCValue")
        self.wofCValue.setGeometry(QRect(544, 118, 120, 16))
        self.wofCValue.setFont(font5)
        self.wofCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wofYLabel = QLabel(self.centralwidget)
        self.wofYLabel.setObjectName(u"wofYLabel")
        self.wofYLabel.setGeometry(QRect(520, 54, 10, 16))
        self.wofYLabel.setFont(font4)
        self.wofBValue = QLabel(self.centralwidget)
        self.wofBValue.setObjectName(u"wofBValue")
        self.wofBValue.setGeometry(QRect(544, 102, 120, 16))
        self.wofBValue.setFont(font5)
        self.wofBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wofXValue = QLabel(self.centralwidget)
        self.wofXValue.setObjectName(u"wofXValue")
        self.wofXValue.setGeometry(QRect(544, 38, 120, 16))
        self.wofXValue.setFont(font5)
        self.wofXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.wofAValue = QLabel(self.centralwidget)
        self.wofAValue.setObjectName(u"wofAValue")
        self.wofAValue.setGeometry(QRect(544, 86, 120, 16))
        self.wofAValue.setFont(font5)
        self.wofAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mtpCValue = QLabel(self.centralwidget)
        self.mtpCValue.setObjectName(u"mtpCValue")
        self.mtpCValue.setGeometry(QRect(43, 254, 120, 16))
        self.mtpCValue.setFont(font5)
        self.mtpCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mtpZLabel = QLabel(self.centralwidget)
        self.mtpZLabel.setObjectName(u"mtpZLabel")
        self.mtpZLabel.setGeometry(QRect(19, 206, 10, 16))
        self.mtpZLabel.setFont(font4)
        self.mtpAValue = QLabel(self.centralwidget)
        self.mtpAValue.setObjectName(u"mtpAValue")
        self.mtpAValue.setGeometry(QRect(43, 222, 120, 16))
        self.mtpAValue.setFont(font5)
        self.mtpAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mtpBLabel = QLabel(self.centralwidget)
        self.mtpBLabel.setObjectName(u"mtpBLabel")
        self.mtpBLabel.setGeometry(QRect(19, 238, 10, 16))
        self.mtpBLabel.setFont(font4)
        self.mtpCLabel = QLabel(self.centralwidget)
        self.mtpCLabel.setObjectName(u"mtpCLabel")
        self.mtpCLabel.setGeometry(QRect(19, 254, 10, 16))
        self.mtpCLabel.setFont(font4)
        self.mtpXValue = QLabel(self.centralwidget)
        self.mtpXValue.setObjectName(u"mtpXValue")
        self.mtpXValue.setGeometry(QRect(43, 174, 120, 16))
        self.mtpXValue.setFont(font5)
        self.mtpXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mtpALabel = QLabel(self.centralwidget)
        self.mtpALabel.setObjectName(u"mtpALabel")
        self.mtpALabel.setGeometry(QRect(19, 222, 10, 16))
        self.mtpALabel.setFont(font4)
        self.mtpBValue = QLabel(self.centralwidget)
        self.mtpBValue.setObjectName(u"mtpBValue")
        self.mtpBValue.setGeometry(QRect(43, 238, 120, 16))
        self.mtpBValue.setFont(font5)
        self.mtpBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mtpZValue = QLabel(self.centralwidget)
        self.mtpZValue.setObjectName(u"mtpZValue")
        self.mtpZValue.setGeometry(QRect(43, 206, 120, 16))
        self.mtpZValue.setFont(font5)
        self.mtpZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mtpXLabel = QLabel(self.centralwidget)
        self.mtpXLabel.setObjectName(u"mtpXLabel")
        self.mtpXLabel.setGeometry(QRect(19, 174, 10, 16))
        self.mtpXLabel.setFont(font4)
        self.mtpYLabel = QLabel(self.centralwidget)
        self.mtpYLabel.setObjectName(u"mtpYLabel")
        self.mtpYLabel.setGeometry(QRect(19, 190, 10, 16))
        self.mtpYLabel.setFont(font4)
        self.mtpYValue = QLabel(self.centralwidget)
        self.mtpYValue.setObjectName(u"mtpYValue")
        self.mtpYValue.setGeometry(QRect(43, 190, 120, 16))
        self.mtpYValue.setFont(font5)
        self.mtpYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ptpCLabel = QLabel(self.centralwidget)
        self.ptpCLabel.setObjectName(u"ptpCLabel")
        self.ptpCLabel.setGeometry(QRect(187, 254, 10, 16))
        self.ptpCLabel.setFont(font4)
        self.ptpALabel = QLabel(self.centralwidget)
        self.ptpALabel.setObjectName(u"ptpALabel")
        self.ptpALabel.setGeometry(QRect(187, 222, 10, 16))
        self.ptpALabel.setFont(font4)
        self.ptpBLabel = QLabel(self.centralwidget)
        self.ptpBLabel.setObjectName(u"ptpBLabel")
        self.ptpBLabel.setGeometry(QRect(187, 238, 10, 16))
        self.ptpBLabel.setFont(font4)
        self.ptpXValue = QLabel(self.centralwidget)
        self.ptpXValue.setObjectName(u"ptpXValue")
        self.ptpXValue.setGeometry(QRect(211, 174, 120, 16))
        self.ptpXValue.setFont(font5)
        self.ptpXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ptpAValue = QLabel(self.centralwidget)
        self.ptpAValue.setObjectName(u"ptpAValue")
        self.ptpAValue.setGeometry(QRect(211, 222, 120, 16))
        self.ptpAValue.setFont(font5)
        self.ptpAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ptpYValue = QLabel(self.centralwidget)
        self.ptpYValue.setObjectName(u"ptpYValue")
        self.ptpYValue.setGeometry(QRect(211, 190, 120, 16))
        self.ptpYValue.setFont(font5)
        self.ptpYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ptpXLabel = QLabel(self.centralwidget)
        self.ptpXLabel.setObjectName(u"ptpXLabel")
        self.ptpXLabel.setGeometry(QRect(187, 174, 10, 16))
        self.ptpXLabel.setFont(font4)
        self.ptpZLabel = QLabel(self.centralwidget)
        self.ptpZLabel.setObjectName(u"ptpZLabel")
        self.ptpZLabel.setGeometry(QRect(187, 206, 10, 16))
        self.ptpZLabel.setFont(font4)
        self.ptpCValue = QLabel(self.centralwidget)
        self.ptpCValue.setObjectName(u"ptpCValue")
        self.ptpCValue.setGeometry(QRect(211, 254, 120, 16))
        self.ptpCValue.setFont(font5)
        self.ptpCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ptpBValue = QLabel(self.centralwidget)
        self.ptpBValue.setObjectName(u"ptpBValue")
        self.ptpBValue.setGeometry(QRect(211, 238, 120, 16))
        self.ptpBValue.setFont(font5)
        self.ptpBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ptpYLabel = QLabel(self.centralwidget)
        self.ptpYLabel.setObjectName(u"ptpYLabel")
        self.ptpYLabel.setGeometry(QRect(187, 190, 10, 16))
        self.ptpYLabel.setFont(font4)
        self.ptpZValue = QLabel(self.centralwidget)
        self.ptpZValue.setObjectName(u"ptpZValue")
        self.ptpZValue.setGeometry(QRect(211, 206, 120, 16))
        self.ptpZValue.setFont(font5)
        self.ptpZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopAValue = QLabel(self.centralwidget)
        self.jopAValue.setObjectName(u"jopAValue")
        self.jopAValue.setGeometry(QRect(379, 222, 120, 16))
        self.jopAValue.setFont(font5)
        self.jopAValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopYLabel = QLabel(self.centralwidget)
        self.jopYLabel.setObjectName(u"jopYLabel")
        self.jopYLabel.setGeometry(QRect(355, 190, 10, 16))
        self.jopYLabel.setFont(font4)
        self.jopCValue = QLabel(self.centralwidget)
        self.jopCValue.setObjectName(u"jopCValue")
        self.jopCValue.setGeometry(QRect(379, 254, 120, 16))
        self.jopCValue.setFont(font5)
        self.jopCValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopALabel = QLabel(self.centralwidget)
        self.jopALabel.setObjectName(u"jopALabel")
        self.jopALabel.setGeometry(QRect(355, 222, 10, 16))
        self.jopALabel.setFont(font4)
        self.jopYValue = QLabel(self.centralwidget)
        self.jopYValue.setObjectName(u"jopYValue")
        self.jopYValue.setGeometry(QRect(379, 190, 120, 16))
        self.jopYValue.setFont(font5)
        self.jopYValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopBValue = QLabel(self.centralwidget)
        self.jopBValue.setObjectName(u"jopBValue")
        self.jopBValue.setGeometry(QRect(379, 238, 120, 16))
        self.jopBValue.setFont(font5)
        self.jopBValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopCLabel = QLabel(self.centralwidget)
        self.jopCLabel.setObjectName(u"jopCLabel")
        self.jopCLabel.setGeometry(QRect(355, 254, 10, 16))
        self.jopCLabel.setFont(font4)
        self.jopZLabel = QLabel(self.centralwidget)
        self.jopZLabel.setObjectName(u"jopZLabel")
        self.jopZLabel.setGeometry(QRect(355, 206, 10, 16))
        self.jopZLabel.setFont(font4)
        self.jopXLabel = QLabel(self.centralwidget)
        self.jopXLabel.setObjectName(u"jopXLabel")
        self.jopXLabel.setGeometry(QRect(355, 174, 10, 16))
        self.jopXLabel.setFont(font4)
        self.jopBLabel = QLabel(self.centralwidget)
        self.jopBLabel.setObjectName(u"jopBLabel")
        self.jopBLabel.setGeometry(QRect(355, 238, 10, 16))
        self.jopBLabel.setFont(font4)
        self.jopZValue = QLabel(self.centralwidget)
        self.jopZValue.setObjectName(u"jopZValue")
        self.jopZValue.setGeometry(QRect(379, 206, 120, 16))
        self.jopZValue.setFont(font5)
        self.jopZValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopXValue = QLabel(self.centralwidget)
        self.jopXValue.setObjectName(u"jopXValue")
        self.jopXValue.setGeometry(QRect(379, 174, 120, 16))
        self.jopXValue.setFont(font5)
        self.jopXValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spindleStatusValue = QLabel(self.centralwidget)
        self.spindleStatusValue.setObjectName(u"spindleStatusValue")
        self.spindleStatusValue.setGeometry(QRect(608, 174, 61, 20))
        self.spindleStatusValue.setFont(font5)
        self.spindleStatusValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.spindleStatusLabel = QLabel(self.centralwidget)
        self.spindleStatusLabel.setObjectName(u"spindleStatusLabel")
        self.spindleStatusLabel.setGeometry(QRect(525, 174, 78, 16))
        self.spindleStatusLabel.setFont(font4)
        self.plannedTimeLabel = QLabel(self.centralwidget)
        self.plannedTimeLabel.setObjectName(u"plannedTimeLabel")
        self.plannedTimeLabel.setGeometry(QRect(525, 254, 78, 16))
        self.plannedTimeLabel.setFont(font4)
        self.gcodeLineValue = QLabel(self.centralwidget)
        self.gcodeLineValue.setObjectName(u"gcodeLineValue")
        self.gcodeLineValue.setGeometry(QRect(608, 222, 61, 20))
        self.gcodeLineValue.setFont(font5)
        self.gcodeLineValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopZValue_2 = QLabel(self.centralwidget)
        self.jopZValue_2.setObjectName(u"jopZValue_2")
        self.jopZValue_2.setGeometry(QRect(608, 206, 61, 20))
        self.jopZValue_2.setFont(font5)
        self.jopZValue_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.workedTimeLabel = QLabel(self.centralwidget)
        self.workedTimeLabel.setObjectName(u"workedTimeLabel")
        self.workedTimeLabel.setGeometry(QRect(525, 238, 78, 16))
        self.workedTimeLabel.setFont(font4)
        self.workedTimeValue = QLabel(self.centralwidget)
        self.workedTimeValue.setObjectName(u"workedTimeValue")
        self.workedTimeValue.setGeometry(QRect(608, 238, 61, 20))
        self.workedTimeValue.setFont(font5)
        self.workedTimeValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.coolantMistLabel = QLabel(self.centralwidget)
        self.coolantMistLabel.setObjectName(u"coolantMistLabel")
        self.coolantMistLabel.setGeometry(QRect(525, 190, 78, 16))
        self.coolantMistLabel.setFont(font4)
        self.gcodeLineLabel = QLabel(self.centralwidget)
        self.gcodeLineLabel.setObjectName(u"gcodeLineLabel")
        self.gcodeLineLabel.setGeometry(QRect(525, 222, 78, 16))
        self.gcodeLineLabel.setFont(font4)
        self.plannedTimeValue = QLabel(self.centralwidget)
        self.plannedTimeValue.setObjectName(u"plannedTimeValue")
        self.plannedTimeValue.setGeometry(QRect(608, 254, 61, 20))
        self.plannedTimeValue.setFont(font5)
        self.plannedTimeValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jopZLabel_2 = QLabel(self.centralwidget)
        self.jopZLabel_2.setObjectName(u"jopZLabel_2")
        self.jopZLabel_2.setGeometry(QRect(525, 206, 78, 16))
        self.jopZLabel_2.setFont(font4)
        self.coolantMistValue = QLabel(self.centralwidget)
        self.coolantMistValue.setObjectName(u"coolantMistValue")
        self.coolantMistValue.setGeometry(QRect(608, 190, 61, 20))
        self.coolantMistValue.setFont(font5)
        self.coolantMistValue.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.apiServerHostPortLabel = QLabel(self.centralwidget)
        self.apiServerHostPortLabel.setObjectName(u"apiServerHostPortLabel")
        self.apiServerHostPortLabel.setGeometry(QRect(8, 709, 129, 22))
        sizePolicy.setHeightForWidth(self.apiServerHostPortLabel.sizePolicy().hasHeightForWidth())
        self.apiServerHostPortLabel.setSizePolicy(sizePolicy)
        font6 = QFont()
        font6.setFamilies([u"Tahoma"])
        font6.setPointSize(10)
        self.apiServerHostPortLabel.setFont(font6)
        self.apiServerHostPortLabel.setScaledContents(False)
        self.apiServerHostEdit = QLineEdit(self.centralwidget)
        self.apiServerHostEdit.setObjectName(u"apiServerHostEdit")
        self.apiServerHostEdit.setGeometry(QRect(144, 709, 100, 22))
        self.apiServerPortEdit = QLineEdit(self.centralwidget)
        self.apiServerPortEdit.setObjectName(u"apiServerPortEdit")
        self.apiServerPortEdit.setGeometry(QRect(248, 709, 80, 22))
        self.useTLSCheckBox = QCheckBox(self.centralwidget)
        self.useTLSCheckBox.setObjectName(u"useTLSCheckBox")
        self.useTLSCheckBox.setGeometry(QRect(336, 709, 97, 22))
        self.stayOnTopCheckBox = QCheckBox(self.centralwidget)
        self.stayOnTopCheckBox.setObjectName(u"stayOnTopCheckBox")
        self.stayOnTopCheckBox.setGeometry(QRect(440, 709, 89, 22))
        DesktopView.setCentralWidget(self.centralwidget)
        self.StatusBar = QStatusBar(DesktopView)
        self.StatusBar.setObjectName(u"StatusBar")
        DesktopView.setStatusBar(self.StatusBar)

        self.retranslateUi(DesktopView)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(DesktopView)
    # setupUi

    def retranslateUi(self, DesktopView):
        DesktopView.setWindowTitle(QCoreApplication.translate("DesktopView", u"API Client Engine Demo", None))
        self.new_program.setText(QCoreApplication.translate("DesktopView", u"New Program", None))
        self.ProgramLoadButton.setText(QCoreApplication.translate("DesktopView", u"Load Program", None))
        self.ProgramSaveButton.setText(QCoreApplication.translate("DesktopView", u"Save Program", None))
        self.ProgramSaveAsButton.setText(QCoreApplication.translate("DesktopView", u"Save Program As", None))
        self.label.setText(QCoreApplication.translate("DesktopView", u"NEW PROGRAM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProgram), QCoreApplication.translate("DesktopView", u"Program", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGCode), QCoreApplication.translate("DesktopView", u"G-Code", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCNC), QCoreApplication.translate("DesktopView", u"CNC", None))
        self.cncJogCommandXMButton.setText(QCoreApplication.translate("DesktopView", u"X -", None))
        self.cncJogCommandYMButton.setText(QCoreApplication.translate("DesktopView", u"Y -", None))
        self.cncJogCommandZMButton.setText(QCoreApplication.translate("DesktopView", u"Z -", None))
        self.cncJogCommandAMButton.setText(QCoreApplication.translate("DesktopView", u"A -", None))
        self.cncJogCommandBMButton.setText(QCoreApplication.translate("DesktopView", u"B -", None))
        self.cncJogCommandCMButton.setText(QCoreApplication.translate("DesktopView", u"C -", None))
        self.cncJogCommandYPButton.setText(QCoreApplication.translate("DesktopView", u"Y +", None))
        self.cncJogCommandAPButton.setText(QCoreApplication.translate("DesktopView", u"A +", None))
        self.cncJogCommandBPButton.setText(QCoreApplication.translate("DesktopView", u"B +", None))
        self.cncJogCommandXPButton.setText(QCoreApplication.translate("DesktopView", u"X +", None))
        self.cncJogCommandCPButton.setText(QCoreApplication.translate("DesktopView", u"C +", None))
        self.cncJogCommandZPButton.setText(QCoreApplication.translate("DesktopView", u"Z +", None))
        self.pushButton_13.setText(QCoreApplication.translate("DesktopView", u"Set Y", None))
        self.pushButton_14.setText(QCoreApplication.translate("DesktopView", u"Set C", None))
        self.pushButton_15.setText(QCoreApplication.translate("DesktopView", u"Set X", None))
        self.pushButton_16.setText(QCoreApplication.translate("DesktopView", u"Set B", None))
        self.pushButton_17.setText(QCoreApplication.translate("DesktopView", u"Set A", None))
        self.pushButton_18.setText(QCoreApplication.translate("DesktopView", u"Set Z", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJOG), QCoreApplication.translate("DesktopView", u"JOG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOverrides), QCoreApplication.translate("DesktopView", u"Overrides", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHoming), QCoreApplication.translate("DesktopView", u"Homing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMDI), QCoreApplication.translate("DesktopView", u"MDI", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDIO), QCoreApplication.translate("DesktopView", u"D I/O", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAIO), QCoreApplication.translate("DesktopView", u"A I/O", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabScanningLaser), QCoreApplication.translate("DesktopView", u"Scanning Laser", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMachiningInfo), QCoreApplication.translate("DesktopView", u"Machining Info", None))
        self.uidAboutButton.setText(QCoreApplication.translate("DesktopView", u"About...", None))
        self.uidATCManagementButton.setText(QCoreApplication.translate("DesktopView", u"ATC Management", None))
        self.uidBoardEtherCATMonitorButton.setText(QCoreApplication.translate("DesktopView", u"Board EtherCAT Monitor...", None))
        self.uidBoardFirmwareManagerButton.setText(QCoreApplication.translate("DesktopView", u"Board Firmware Manager...", None))
        self.uidBoardMonitorButton.setText(QCoreApplication.translate("DesktopView", u"Board Monitor...", None))
        self.uidBoardSettingsButton.setText(QCoreApplication.translate("DesktopView", u"Board Settings...", None))
        self.uidToolsLibraryButton.setText(QCoreApplication.translate("DesktopView", u"Tools Library...", None))
        self.uidChangeBoardIPButton.setText(QCoreApplication.translate("DesktopView", u"Change Board IP...", None))
        self.uidWorkCoordinatesButton.setText(QCoreApplication.translate("DesktopView", u"Work Coordinates...", None))
        self.uidProgramSettingsButton.setText(QCoreApplication.translate("DesktopView", u"Program Settings...", None))
        self.uidParametersLibraryButton.setText(QCoreApplication.translate("DesktopView", u"Parameters Library...", None))
        self.uidMacrosManagementButton.setText(QCoreApplication.translate("DesktopView", u"Macros Management", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUIDialogs), QCoreApplication.translate("DesktopView", u"UI Dialogs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSystemInfo), QCoreApplication.translate("DesktopView", u"System Info", None))
        self.mcsTitleLabel.setText(QCoreApplication.translate("DesktopView", u"MACHINE POSITIONS", None))
        self.prpTitleLabel.setText(QCoreApplication.translate("DesktopView", u"PROGRAM POSITIONS", None))
        self.avlTitleLabel.setText(QCoreApplication.translate("DesktopView", u"ACTUAL VELOCITIES", None))
        self.wofTitleLabel.setText(QCoreApplication.translate("DesktopView", u"WORKING OFFSETS", None))
        self.mtpTitleLabel.setText(QCoreApplication.translate("DesktopView", u"MAC SET POSITIONS", None))
        self.ptpTitleLabel.setText(QCoreApplication.translate("DesktopView", u"PRG SET POSITIONS", None))
        self.jopTitleLabel.setText(QCoreApplication.translate("DesktopView", u"JOINT POSITIONS", None))
        self.machineInfoLabel.setText(QCoreApplication.translate("DesktopView", u"MACHINE INFO", None))
        self.toolInfoLabel.setText("")
        self.CommandsLabel.setText(QCoreApplication.translate("DesktopView", u"COMMANDS", None))
        self.CNCConnectionOpenButton.setText(QCoreApplication.translate("DesktopView", u"OPEN\n"
"Connection", None))
        self.CNCConnectionCloseButton.setText(QCoreApplication.translate("DesktopView", u"CLOSE\n"
"Connection", None))
        self.ServerConnectDisconnectButton.setText(QCoreApplication.translate("DesktopView", u"Connect", None))
        self.mcsXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.mcsYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.mcsZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.mcsALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.mcsBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.mcsXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.mcsYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.mcsZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.mcsAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.mcsBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.mcsCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.mcsCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.wcsCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.wcsBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.wcsXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.wcsBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.wcsYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.wcsALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.wcsXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.wcsYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.wcsZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.wcsCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.wcsAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.wcsZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.avlYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mn/min", None))
        self.avlZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mn/min", None))
        self.avlZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.avlXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.avlALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.avlBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.avlCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.avlCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg/min", None))
        self.avlYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.avlBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg/min", None))
        self.avlXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mn/min", None))
        self.avlAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg/min", None))
        self.wofYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.wofZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.wofZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.wofXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.wofALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.wofBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.wofCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.wofCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.wofYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.wofBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.wofXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.wofAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.mtpCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.mtpZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.mtpAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.mtpBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.mtpCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.mtpXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.mtpALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.mtpBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.mtpZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.mtpXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.mtpYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.mtpYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.ptpCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.ptpALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.ptpBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.ptpXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.ptpAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.ptpYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.ptpXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.ptpZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.ptpCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.ptpBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.ptpYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.ptpZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.jopAValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.jopYLabel.setText(QCoreApplication.translate("DesktopView", u"Y", None))
        self.jopCValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.jopALabel.setText(QCoreApplication.translate("DesktopView", u"A", None))
        self.jopYValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.jopBValue.setText(QCoreApplication.translate("DesktopView", u"0.0 dg", None))
        self.jopCLabel.setText(QCoreApplication.translate("DesktopView", u"C", None))
        self.jopZLabel.setText(QCoreApplication.translate("DesktopView", u"Z", None))
        self.jopXLabel.setText(QCoreApplication.translate("DesktopView", u"X", None))
        self.jopBLabel.setText(QCoreApplication.translate("DesktopView", u"B", None))
        self.jopZValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.jopXValue.setText(QCoreApplication.translate("DesktopView", u"0.0 mm", None))
        self.spindleStatusValue.setText(QCoreApplication.translate("DesktopView", u"0", None))
        self.spindleStatusLabel.setText(QCoreApplication.translate("DesktopView", u"Spindle", None))
        self.plannedTimeLabel.setText(QCoreApplication.translate("DesktopView", u"Planned Time", None))
        self.gcodeLineValue.setText(QCoreApplication.translate("DesktopView", u"0", None))
        self.jopZValue_2.setText(QCoreApplication.translate("DesktopView", u"OFF", None))
        self.workedTimeLabel.setText(QCoreApplication.translate("DesktopView", u"Worked Time", None))
        self.workedTimeValue.setText(QCoreApplication.translate("DesktopView", u"00:00:00", None))
        self.coolantMistLabel.setText(QCoreApplication.translate("DesktopView", u"Mist", None))
        self.gcodeLineLabel.setText(QCoreApplication.translate("DesktopView", u"GCode Line", None))
        self.plannedTimeValue.setText(QCoreApplication.translate("DesktopView", u"00:00:00", None))
        self.jopZLabel_2.setText(QCoreApplication.translate("DesktopView", u"Flood", None))
        self.coolantMistValue.setText(QCoreApplication.translate("DesktopView", u"OFF", None))
        self.apiServerHostPortLabel.setText(QCoreApplication.translate("DesktopView", u"API Server Host & Port", None))
        self.useTLSCheckBox.setText(QCoreApplication.translate("DesktopView", u"Use TLS 1.2", None))
        self.stayOnTopCheckBox.setText(QCoreApplication.translate("DesktopView", u"Stay on Top", None))
    # retranslateUi

