# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user_media_dialogznKEVu.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)

class Ui_UserMediaDialog(object):
    def setupUi(self, UserMediaDialog):
        if not UserMediaDialog.objectName():
            UserMediaDialog.setObjectName(u"UserMediaDialog")
        UserMediaDialog.resize(450, 460)
        self.stopButton = QPushButton(UserMediaDialog)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setGeometry(QRect(110, 410, 101, 41))
        self.stopButton.setAutoDefault(False)
        self.continueButton = QPushButton(UserMediaDialog)
        self.continueButton.setObjectName(u"continueButton")
        self.continueButton.setGeometry(QRect(220, 410, 101, 41))
        self.continueButton.setAutoDefault(False)
        self.requestLabel = QLabel(UserMediaDialog)
        self.requestLabel.setObjectName(u"requestLabel")
        self.requestLabel.setGeometry(QRect(0, 0, 450, 100))
        self.requestEdit01 = QLineEdit(UserMediaDialog)
        self.requestEdit01.setObjectName(u"requestEdit01")
        self.requestEdit01.setGeometry(QRect(65, 105, 320, 27))
        font = QFont()
        font.setFamilies([u"Tahoma"])
        font.setPointSize(12)
        self.requestEdit01.setFont(font)
        self.requestEdit01.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit02 = QLineEdit(UserMediaDialog)
        self.requestEdit02.setObjectName(u"requestEdit02")
        self.requestEdit02.setGeometry(QRect(65, 135, 320, 27))
        self.requestEdit02.setFont(font)
        self.requestEdit02.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit03 = QLineEdit(UserMediaDialog)
        self.requestEdit03.setObjectName(u"requestEdit03")
        self.requestEdit03.setGeometry(QRect(65, 165, 320, 27))
        self.requestEdit03.setFont(font)
        self.requestEdit03.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit04 = QLineEdit(UserMediaDialog)
        self.requestEdit04.setObjectName(u"requestEdit04")
        self.requestEdit04.setGeometry(QRect(65, 195, 320, 27))
        self.requestEdit04.setFont(font)
        self.requestEdit04.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit05 = QLineEdit(UserMediaDialog)
        self.requestEdit05.setObjectName(u"requestEdit05")
        self.requestEdit05.setGeometry(QRect(65, 225, 320, 27))
        self.requestEdit05.setFont(font)
        self.requestEdit05.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit06 = QLineEdit(UserMediaDialog)
        self.requestEdit06.setObjectName(u"requestEdit06")
        self.requestEdit06.setGeometry(QRect(65, 255, 320, 27))
        self.requestEdit06.setFont(font)
        self.requestEdit06.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit07 = QLineEdit(UserMediaDialog)
        self.requestEdit07.setObjectName(u"requestEdit07")
        self.requestEdit07.setGeometry(QRect(65, 285, 320, 27))
        self.requestEdit07.setFont(font)
        self.requestEdit07.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit08 = QLineEdit(UserMediaDialog)
        self.requestEdit08.setObjectName(u"requestEdit08")
        self.requestEdit08.setGeometry(QRect(65, 315, 320, 27))
        self.requestEdit08.setFont(font)
        self.requestEdit08.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit09 = QLineEdit(UserMediaDialog)
        self.requestEdit09.setObjectName(u"requestEdit09")
        self.requestEdit09.setGeometry(QRect(65, 345, 320, 27))
        self.requestEdit09.setFont(font)
        self.requestEdit09.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestEdit10 = QLineEdit(UserMediaDialog)
        self.requestEdit10.setObjectName(u"requestEdit10")
        self.requestEdit10.setGeometry(QRect(65, 375, 320, 27))
        self.requestEdit10.setFont(font)
        self.requestEdit10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.requestLabel01 = QLabel(UserMediaDialog)
        self.requestLabel01.setObjectName(u"requestLabel01")
        self.requestLabel01.setGeometry(QRect(20, 105, 31, 26))
        self.requestLabel01.setFont(font)
        self.requestLabel01.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel02 = QLabel(UserMediaDialog)
        self.requestLabel02.setObjectName(u"requestLabel02")
        self.requestLabel02.setGeometry(QRect(20, 135, 31, 26))
        self.requestLabel02.setFont(font)
        self.requestLabel02.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel03 = QLabel(UserMediaDialog)
        self.requestLabel03.setObjectName(u"requestLabel03")
        self.requestLabel03.setGeometry(QRect(20, 165, 31, 26))
        self.requestLabel03.setFont(font)
        self.requestLabel03.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel04 = QLabel(UserMediaDialog)
        self.requestLabel04.setObjectName(u"requestLabel04")
        self.requestLabel04.setGeometry(QRect(20, 195, 31, 26))
        self.requestLabel04.setFont(font)
        self.requestLabel04.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel05 = QLabel(UserMediaDialog)
        self.requestLabel05.setObjectName(u"requestLabel05")
        self.requestLabel05.setGeometry(QRect(20, 225, 31, 26))
        self.requestLabel05.setFont(font)
        self.requestLabel05.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel06 = QLabel(UserMediaDialog)
        self.requestLabel06.setObjectName(u"requestLabel06")
        self.requestLabel06.setGeometry(QRect(20, 255, 31, 26))
        self.requestLabel06.setFont(font)
        self.requestLabel06.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel07 = QLabel(UserMediaDialog)
        self.requestLabel07.setObjectName(u"requestLabel07")
        self.requestLabel07.setGeometry(QRect(20, 285, 31, 26))
        self.requestLabel07.setFont(font)
        self.requestLabel07.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel08 = QLabel(UserMediaDialog)
        self.requestLabel08.setObjectName(u"requestLabel08")
        self.requestLabel08.setGeometry(QRect(20, 315, 31, 26))
        self.requestLabel08.setFont(font)
        self.requestLabel08.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel09 = QLabel(UserMediaDialog)
        self.requestLabel09.setObjectName(u"requestLabel09")
        self.requestLabel09.setGeometry(QRect(20, 345, 31, 26))
        self.requestLabel09.setFont(font)
        self.requestLabel09.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.requestLabel10 = QLabel(UserMediaDialog)
        self.requestLabel10.setObjectName(u"requestLabel10")
        self.requestLabel10.setGeometry(QRect(20, 375, 31, 26))
        self.requestLabel10.setFont(font)
        self.requestLabel10.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.dialogFrame = QFrame(UserMediaDialog)
        self.dialogFrame.setObjectName(u"dialogFrame")
        self.dialogFrame.setGeometry(QRect(0, 0, 450, 460))
        self.dialogFrame.setFrameShape(QFrame.Shape.Box)
        self.dialogFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.dialogFrame.setLineWidth(2)
        self.dialogFrame.raise_()
        self.requestLabel.raise_()
        self.stopButton.raise_()
        self.continueButton.raise_()
        self.requestEdit01.raise_()
        self.requestEdit02.raise_()
        self.requestEdit03.raise_()
        self.requestEdit04.raise_()
        self.requestEdit05.raise_()
        self.requestEdit06.raise_()
        self.requestEdit07.raise_()
        self.requestEdit08.raise_()
        self.requestEdit09.raise_()
        self.requestEdit10.raise_()
        self.requestLabel01.raise_()
        self.requestLabel02.raise_()
        self.requestLabel03.raise_()
        self.requestLabel04.raise_()
        self.requestLabel05.raise_()
        self.requestLabel06.raise_()
        self.requestLabel07.raise_()
        self.requestLabel08.raise_()
        self.requestLabel09.raise_()
        self.requestLabel10.raise_()

        self.retranslateUi(UserMediaDialog)

        QMetaObject.connectSlotsByName(UserMediaDialog)
    # setupUi

    def retranslateUi(self, UserMediaDialog):
        UserMediaDialog.setWindowTitle(QCoreApplication.translate("UserMediaDialog", u"Dialog", None))
        self.stopButton.setText(QCoreApplication.translate("UserMediaDialog", u"STOP", None))
        self.continueButton.setText(QCoreApplication.translate("UserMediaDialog", u"CONTINUE", None))
        self.requestLabel.setText("")
        self.requestEdit01.setText("")
        self.requestEdit02.setText("")
        self.requestEdit03.setText("")
        self.requestEdit04.setText("")
        self.requestEdit05.setText("")
        self.requestEdit06.setText("")
        self.requestEdit07.setText("")
        self.requestEdit08.setText("")
        self.requestEdit09.setText("")
        self.requestEdit10.setText("")
        self.requestLabel01.setText(QCoreApplication.translate("UserMediaDialog", u"1 :", None))
        self.requestLabel02.setText(QCoreApplication.translate("UserMediaDialog", u"2 :", None))
        self.requestLabel03.setText(QCoreApplication.translate("UserMediaDialog", u"3 :", None))
        self.requestLabel04.setText(QCoreApplication.translate("UserMediaDialog", u"4 :", None))
        self.requestLabel05.setText(QCoreApplication.translate("UserMediaDialog", u"5 :", None))
        self.requestLabel06.setText(QCoreApplication.translate("UserMediaDialog", u"6 :", None))
        self.requestLabel07.setText(QCoreApplication.translate("UserMediaDialog", u"7 :", None))
        self.requestLabel08.setText(QCoreApplication.translate("UserMediaDialog", u"8 :", None))
        self.requestLabel09.setText(QCoreApplication.translate("UserMediaDialog", u"9 :", None))
        self.requestLabel10.setText(QCoreApplication.translate("UserMediaDialog", u"10 :", None))
    # retranslateUi

